### ISSUE TITLE
Unable to create user in News

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#36]
When creating any user in **News**, after pressing **signup**, the app navigates to `http://localhost:8080/y` and gives the following error in the arc REPL:

```
arc> rename-file-or-directory: cannot rename file or directory
  source path: /var/tmp/cooks.14569798801456979880387
  dest path: /home/pelle/anarki/www/cooks
  system error: Invalid cross-device link; errno=18
  context...:
   /home/pelle/anarki/ac.scm:1153:13: mvfile
    signup-handler
    respond
    handle-request-thread
```

Just tested: Creating user works fine in **News** on **arc3.1** here, but fails in **anarki** with above error.

**Comment by akkartik** [comment]
What platform are you on?

**Comment by hjek** [comment]
Ubuntu Wily. Racket v6.2.

**Comment by akkartik** [comment]
I just tried it and got a *different* error at the same place on OS X:

```
Type: unknown type
#<path:/var/folders/y_/00rkkq753tgf_n4qmg5njs4c003hjl/T/shash.14569804421456980442880>
  context...:
    ar-coerce
    +
    shash
    shash
    set-pw
    set-pw
    create-acct
    signup-handler
    respond
    handle-request-thread
    handle-request-thread
user break
  context...:
    socket-accept
    accept-request-with-deadline
    recur
   zz
```

My first guess is to suspect
https://github.com/arclanguage/anarki/commit/7ae9fbc7825d65513ff4e3cc6e518ef502de8236.
Can you try undoing it and see if the problem goes away? It fixes the error
on OS X.

**Comment by akkartik** [comment]
I can reproduce your error on Linux. My suggestion doesn't fix it. I think
it might be because `/tmp` is usually on a separate partition on Linux..

**Comment by hjek** [comment]
Did `git reset --hard 7ae9fbc` but it didn't solve problem.

**Comment by hjek** [comment]
I only have one disk partition.

**Comment by hjek** [comment]
Went really far back in the history to a commit from 2009, and there it works fine, and tried from my first commit in 2015 where it doesn't work. It seems silly to just do binary search through the git history until the commit introducing the error is narrowed down. There should be some cool git feature for that.

**Comment by akkartik** [comment]
`git bisect`? :)

As an experiment I tried running it from /tmp on my machine, and the error
went away. Can you try that as well, *after* making that `mktemp` change I
mentioned above? Very strange to have two distinct issues hit us in the
same place.

I think 2009 probably didn't use the system's `mktemp` function. Maybe
that's the problem.

**Comment by hjek** [comment]
Tried running **News** from `/tmp`, and on creating a user, this error shows:

```
/tmp/anarki$ ./run-news 
rm: cannot remove ‘www/news/story/*.tmp’: No such file or directory
load items: 
ranking stories.
ready to serve port 8080

To quit:
  arc> (quit)
  (or press ctrl and 'd' at once)
For help on say 'string':
  arc> (help string)
For a list of differences with arc 3.1:
  arc> (incompatibilities)
To run all automatic tests:
  $ hg clone https://bitbucket.org/zck/unit-test.arc
  $ ./arc
  arc> (load "tests.arc")

If you have questions or get stuck, come to http://arclanguage.com/forum.
Arc 3.1 documentation: https://arclanguage.github.io/ref.
arc> Type: unknown type #<path:/var/tmp/shash.14569827321456982732871>
  context...:
   /tmp/anarki/ac.scm:1002:0: ar-coerce
   /tmp/anarki/ac.scm:752:8: +
    shash
    shash
    set-pw
```

**Comment by akkartik** [comment]
Yes, that is fixed by undoing
https://github.com/arclanguage/anarki/commit/7ae9fbc7825d65513ff4e3cc6e518ef502de8236

**Comment by hjek** [comment]
Even after that particular commit is undone, the error is still happening. Might do `git bisect`; looks nice.

**Comment by akkartik** [comment]
Very strange!

**Comment by hjek** [comment]
@akkartik , the fix you made for #37 partly fixes this: I can create user in **News** when it is run from `/tmp/`. I think the remaining issue has to do with some way **Ubuntu** handles `/tmp/`, but I assume I can fix it by changing "/tmp/" to some other folder in `ac.scm`:

```
(define (ar-tmpname)
  (call-with-input-file "/dev/urandom"
    (lambda (rstr)
      (do ((s "/tmp/")
           (c (read-char rstr) (read-char rstr))
           (i 0 (+ i 1)))
          ((>= i 16) s)
        (set! s (string-append s
                               (string
                                 (integer->char
                                   (+ (char->integer #\a)
                                      (modulo
                                        (char->integer (read-char rstr))
                                        26))))))))))
```

While I don't need this to run on **Windows**, `/tmp/` and `/dev/urandom` are definitely not gonna work there. And I wonder if it would make sense to:

- change temporary file location from `/tmp` to `tmp` (because of **Ubuntu** and **Windows**)
- instead of `/dev/urandom`, use arc's `(rand)` for the names of the temporary files (because of **Windows**)

**Comment by hjek** [comment]
Oh, `ac.scm` is a **mzcheme** file, so it'll be `(random)` instead of `(rand)`.

**Comment by akkartik** [comment]
I actually thought we'd gotten rid of `ar-tmpname`.. The advantage of
`mktemp` is like you pointed out that it's cross-platform and doesn't rely
on /dev/urandom and so on. The other advantage of `mktemp` is that since
it's for temporary filenames in particular, it has better multi-threaded
properties. It returns the filename only after creating it with an atomic
operation, so if you have lots of threads opening temporary files at once
you're guaranteed to never get a collision.

It turns out that `mktemp` takes a directory argument, so maybe it's just a
matter of changing it to `tmp` or something else?

**Comment by akkartik** [comment]
That seems to work. Submitting now; let me know if that fixes things for
you.

**Comment by hjek** [comment]
Changing `tmpdir*` to `tmp` in `arc.arc` *does* solve the signup and login problem on **Ubuntu**.

**Comment by hjek** [comment]
I'll try your fix before submitting anything. Otherwise moving the temporary folder from "default location" to the anarki folder does the trick. But I think it's a good idea to do `(ensure-dir "tmp")` in that case.

**Comment by akkartik** [comment]
Yeah I noticed that as well :) Actually if you have a commit already in
place you can go ahead and submit. We'll see how I did :)

**Comment by hjek** [comment]
Still had the same error after your commit. I'll push my fix.

**Comment by akkartik** [comment]
:+1:
